package module

import "github.com/golang/protobuf/protoc-gen-go/descriptor"

type protoFile struct {
	Path      string
	GoPackage string
	Messages  []*protoMessage
}

type protoMessage struct {
	Name   string
	Fields []*protoField
}

type protoField struct {
	// Name is protobuf-style field name (snake_case)
	Name string
	// Accessor name when marshaling this field
	Accessor string
	Type     descriptor.FieldDescriptorProto_Type
	IsRepeated bool
}

const tmpl = `// Code generated by protoc-gen-marshal-zap. DO NOT EDIT.
// source: {{ .Path }}

package {{ .GoPackage }}

import  (
	"go.uber.org/zap/zapcore"
)

{{ range .Messages }}
func (m *{{ .Name }}) MarshalLogObject(enc zapcore.ObjectEncoder) error {
	if u == nil {
		return nil
	}

	return nil
}
{{ end }}
`
