// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/message/types.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Types struct {
	Str                  string   `protobuf:"bytes,1,opt,name=str,proto3" json:"str,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Types) Reset()         { *m = Types{} }
func (m *Types) String() string { return proto.CompactTextString(m) }
func (*Types) ProtoMessage()    {}
func (*Types) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c86c08eb4ed5ae4, []int{0}
}

func (m *Types) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Types.Unmarshal(m, b)
}
func (m *Types) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Types.Marshal(b, m, deterministic)
}
func (m *Types) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Types.Merge(m, src)
}
func (m *Types) XXX_Size() int {
	return xxx_messageInfo_Types.Size(m)
}
func (m *Types) XXX_DiscardUnknown() {
	xxx_messageInfo_Types.DiscardUnknown(m)
}

var xxx_messageInfo_Types proto.InternalMessageInfo

func (m *Types) GetStr() string {
	if m != nil {
		return m.Str
	}
	return ""
}

func init() {
	proto.RegisterType((*Types)(nil), "github.com.kei2100.playground_protobuf.message.Types")
}

func init() { proto.RegisterFile("proto/message/types.proto", fileDescriptor_5c86c08eb4ed5ae4) }

var fileDescriptor_5c86c08eb4ed5ae4 = []byte{
	// 135 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2f, 0xa9, 0x2c, 0x48, 0x2d, 0xd6,
	0x03, 0x8b, 0x09, 0xe9, 0xa5, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0x65,
	0xa7, 0x66, 0x1a, 0x19, 0x1a, 0x18, 0xe8, 0x15, 0xe4, 0x24, 0x56, 0xa6, 0x17, 0xe5, 0x97, 0xe6,
	0xa5, 0xc4, 0x83, 0x15, 0x25, 0x95, 0xa6, 0xe9, 0x41, 0xf5, 0x2a, 0x49, 0x72, 0xb1, 0x86, 0x80,
	0xb4, 0x0b, 0x09, 0x70, 0x31, 0x17, 0x97, 0x14, 0x49, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81,
	0x98, 0x4e, 0xc6, 0x51, 0x86, 0x08, 0xc3, 0xf4, 0xa1, 0x86, 0xe9, 0x23, 0x0c, 0xd3, 0x85, 0x19,
	0xa6, 0x9f, 0x0e, 0x77, 0x4b, 0x12, 0x1b, 0x58, 0xd0, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xba,
	0x96, 0xe4, 0xf3, 0xa3, 0x00, 0x00, 0x00,
}
