// Code generated by protoc-gen-marshal-zap. DO NOT EDIT.
// source: github.com/kei2100/playground-protobuf/go/message/types.pb.go

package message

import (
	"go.uber.org/zap/zapcore"
)

func (m *Types) MarshalLogObject(enc zapcore.ObjectEncoder) error {
	if u == nil {
		return nil
	}

	return nil
}

func (m *Types_Nested) MarshalLogObject(enc zapcore.ObjectEncoder) error {
	if u == nil {
		return nil
	}

	return nil
}
