// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/message/hello.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Hello struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hello) Reset()         { *m = Hello{} }
func (m *Hello) String() string { return proto.CompactTextString(m) }
func (*Hello) ProtoMessage()    {}
func (*Hello) Descriptor() ([]byte, []int) {
	return fileDescriptor_e840e18c532a9697, []int{0}
}

func (m *Hello) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hello.Unmarshal(m, b)
}
func (m *Hello) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hello.Marshal(b, m, deterministic)
}
func (m *Hello) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hello.Merge(m, src)
}
func (m *Hello) XXX_Size() int {
	return xxx_messageInfo_Hello.Size(m)
}
func (m *Hello) XXX_DiscardUnknown() {
	xxx_messageInfo_Hello.DiscardUnknown(m)
}

var xxx_messageInfo_Hello proto.InternalMessageInfo

func (m *Hello) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Hello)(nil), "github.com.kei2100.playground_protobuf.message.Hello")
}

func init() { proto.RegisterFile("proto/message/hello.proto", fileDescriptor_e840e18c532a9697) }

var fileDescriptor_e840e18c532a9697 = []byte{
	// 133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0xcf, 0x48, 0xcd, 0xc9, 0xc9, 0xd7,
	0x03, 0x8b, 0x09, 0xe9, 0xa5, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0x65,
	0xa7, 0x66, 0x1a, 0x19, 0x1a, 0x18, 0xe8, 0x15, 0xe4, 0x24, 0x56, 0xa6, 0x17, 0xe5, 0x97, 0xe6,
	0xa5, 0xc4, 0x83, 0x15, 0x25, 0x95, 0xa6, 0xe9, 0x41, 0xf5, 0x2a, 0x29, 0x72, 0xb1, 0x7a, 0x80,
	0xb4, 0x0b, 0x49, 0x70, 0xb1, 0x43, 0xc5, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x60, 0x5c,
	0x27, 0xb3, 0x28, 0x13, 0x84, 0xa1, 0xfa, 0x50, 0x43, 0xf5, 0x11, 0x86, 0xea, 0xc2, 0x0c, 0xd5,
	0x47, 0x71, 0x56, 0x12, 0x1b, 0x98, 0x6b, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x00, 0x26, 0x3e,
	0x4b, 0xae, 0x00, 0x00, 0x00,
}
