// Code generated by protoc-gen-marshal-zap. DO NOT EDIT.
// source: github.com/kei2100/playground-protobuf/proto/marshal-zap/marshal-zap.pb.go

package marshal_zap

import (
	"go.uber.org/zap/zapcore"
	"strconv"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = zapcore.NewNopCore
var _ = strconv.FormatInt
